CREATE TABLE PATIENT (
PATIENT_ID INTEGER NOT NULL UNIQUE PRIMARY KEY,
FULL_NAME VARCHAR(31),
PHONE INTEGER,
EMAIL VARCHAR(39),
ADDRESS VARCHAR(150),
ADDED_DATE DATE,
DOCTOR_ID INT NOT NULL,
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)

);